### ISSUE TITLE
Create Migrations

### ISSUE THREAD

**Issue by GussRw** [GussRw/product-barcode-finder-api#1]
- [x]  users
- [x]  cities
- [x]  products
- [x]  shops
- [x]  products_shops

**Comment by GussRw** [comment]
I think the user migration has already been created

**Comment by AliNava** [comment]
but, you think? or you do?

**Comment by AliNava** [comment]
but, you think? or you do?

**Comment by AliNava** [comment]
I add migrations and fields in cities and  products

**Comment by AliNava** [comment]
We can go to sleep?

**Comment by GussRw** [comment]
hehehe yes, we go to sleep

**Comment by AliNava** [comment]
<3 thanks, loveu so much
